### ISSUE TITLE
What is string16_to_key and why

### ISSUE THREAD

**Issue by sergeevabc** [jedisct1/siphash-js#2]
Dear Frank,
I'm curious of two things related to Siphash, could you be so kind and help me to bring it out?

1. `string16_to_key(key)` As i see, key before conversion is string of 16 chars. Can it be any 16 chars like `/Q<>Vi3F5ZT*?%=F` or they must be strictly based on base16 alphabet (0123456789ABCDEF)? If second option is the only valid, can chars be lowercase or even mixed like abc, aBc?

2. Why does Siphash actually require the key? For example, another one-way hash function, SHA256, requires just one argument, which is string to hash, so no key is required.

**Comment by zackehh** [comment]
@sergeevabc I know this is late but still; 

1. It's strictly a 16 byte input.
2. SipHash uses it to seed your initial input, making it more secure. If you knew the key, you would know half of the input, making it easier to potentially reverse. Having two inputs (both unknown) makes it (currently) not possible.

**Comment by jedisct1** [comment]
In order to be able to use the full keyspace, the proper way to provide the key is as an array of 4 integers.
If they key has to be secret, this is what you should do.

However, the key doesn't always have to be secret. You may want to use the key just as a way to personalize the hash function for your application, so that two applications hashing the same message will produce a different output. In that case, using a meaningful string with the name of your application is fine, and `string16_to_key()` can be used for this.

**Comment by sergeevabc** [comment]
@zackehh and @jedisct1, thank you.
